/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FilesRouteImport } from './routes/files'
import { Route as GeneralGuidesRouteImport } from './routes/general-guides'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as QaRouteImport } from './routes/qa'
import { Route as WindowsHelpRouteImport } from './routes/windows-help'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralGuidesRoute = GeneralGuidesRouteImport.update({
  id: '/general-guides',
  path: '/general-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowsHelpRoute = WindowsHelpRouteImport.update({
  id: '/windows-help',
  path: '/windows-help',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/files': typeof FilesRoute
  '/general-guides': typeof GeneralGuidesRoute
  '/guides': typeof GuidesRoute
  '/qa': typeof QaRoute
  '/windows-help': typeof WindowsHelpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/files': typeof FilesRoute
  '/general-guides': typeof GeneralGuidesRoute
  '/guides': typeof GuidesRoute
  '/qa': typeof QaRoute
  '/windows-help': typeof WindowsHelpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/files': typeof FilesRoute
  '/general-guides': typeof GeneralGuidesRoute
  '/guides': typeof GuidesRoute
  '/qa': typeof QaRoute
  '/windows-help': typeof WindowsHelpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/files'
    | '/general-guides'
    | '/guides'
    | '/qa'
    | '/windows-help'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/files'
    | '/general-guides'
    | '/guides'
    | '/qa'
    | '/windows-help'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/files'
    | '/general-guides'
    | '/guides'
    | '/qa'
    | '/windows-help'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FilesRoute: typeof FilesRoute
  GeneralGuidesRoute: typeof GeneralGuidesRoute
  GuidesRoute: typeof GuidesRoute
  QaRoute: typeof QaRoute
  WindowsHelpRoute: typeof WindowsHelpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-guides': {
      id: '/general-guides'
      path: '/general-guides'
      fullPath: '/general-guides'
      preLoaderRoute: typeof GeneralGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/windows-help': {
      id: '/windows-help'
      path: '/windows-help'
      fullPath: '/windows-help'
      preLoaderRoute: typeof WindowsHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FilesRoute: FilesRoute,
  GeneralGuidesRoute: GeneralGuidesRoute,
  GuidesRoute: GuidesRoute,
  QaRoute: QaRoute,
  WindowsHelpRoute: WindowsHelpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
